### ISSUE TITLE
Installing through Kitematic (Docker) gives no cloudboost.json error

### ISSUE THREAD

**Issue by paishin** [CloudBoost/cloudboost#133]
I am trying to setup a local development environment but when I install cloudboost doker using Kitematic I get the following error:

```
2017-02-16T19:26:15.700188898Z npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.9.5
?25l[..................] - : info using node@v6.9.5 [..................] - : info using node@v6.9.5 ?25hnpm info lifecycle DataServices@1.0.23~prestart: DataServices@1.0.23
?25l[..................] | : info lifecycle DataServices@1.0.23~prestart: DataServi ?25hnpm info lifecycle DataServices@1.0.23~start: DataServices@1.0.23
> DataServices@1.0.23 start /usr/src/app
> node server.js
INFO : SSL Certificate not found or is invalid.
Switching ONLY to HTTP...
{ Error: ENOENT: no such file or directory, open './config/cloudboost.json'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './config/cloudboost.json' }
Server Init...
Data Connections Init...
Looking for a MongoDB Cluster...
INFO : Not running on Docker. Use docker-compose (recommended) from https://github.com/cloudboost/docker
MongoDb connection string:mongodb://localhost:27017/
Setting up Redis...
Setting up Redis with no config....
Setting up Redis take from env variables
Setting up IO adapter
Setting up Analytics...
Analytics URL : 
https://analytics.cloudboost.io
Services Init...
Kickstart database services..
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (/usr/src/app/node_modules/socket.io-redis/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/usr/src/app/node_modules/socket.io-redis/node_modules/redis/index.js:95:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm info lifecycle DataServices@1.0.23~start: Failed to exec start script
npm ERR! Linux 4.4.47-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! DataServices@1.0.23 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DataServices@1.0.23 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the DataServices package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs DataServices
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls DataServices
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by nawazdhandala** [comment]
Did you try installing mongodb and redis containers first?

**Comment by nawazdhandala** [comment]
We also have a Docker Cloud File that you can use to directly install it on any server you like : https://github.com/cloudboost/docker

**Comment by paishin** [comment]
Yes, docker containers for redis and mongodb are already installed.
I have  installed CloudBoost localy (no docker) and it works fine after I
edit the cloudboost.json file and set the IPs to the provided access IP (
192.168.99.100). Its my guess that it fails because for some reason it
cannot find redis and mongo at 127.0.0.1

**Comment by nawazdhandala** [comment]
Can you use our Docker Cloud File to run CloudBoost. It uses multiple services that needs to be connected for it to work properly which is only possible via Docker Compose / Cloud. Let me know if this helps.

**Comment by ganeshan** [comment]
Is there a specific technical reason to no longer support docker-compose.yml? It is so helpful to run the stack on a Mac. Please restore ability to set up CloudBoost on a local Docker instance on a laptop.
